In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras import backend as K
import tensorflow as tf
emotion_model = Sequential()

emotion_model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(48,48,1)))
emotion_model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
emotion_model.add(MaxPooling2D(pool_size=(2, 2)))
emotion_model.add(Dropout(0.25))

emotion_model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
emotion_model.add(MaxPooling2D(pool_size=(2, 2)))
emotion_model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
emotion_model.add(MaxPooling2D(pool_size=(2, 2)))
emotion_model.add(Dropout(0.25))

emotion_model.add(Flatten())
emotion_model.add(Dense(1024, activation='relu'))
emotion_model.add(Dropout(0.5))
emotion_model.add(Dense(7, activation='softmax'))

In [5]:
emotion_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 46, 46, 32)        320       
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 44, 44, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 22, 22, 64)        0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 22, 22, 64)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 20, 20, 128)       73856     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 8, 8, 128)        

In [6]:
import numpy as np
import argparse
import imutils
import time
import cv2
import tensorflow as tf
from model import FacialExpressionModel
facec = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
#new_model = tf.keras.models.load_model('NewEmotion.hp5')
from tensorflow.keras.models import model_from_json
test_model = FacialExpressionModel("model.json", "model_weights.h5")
emotion_dict = {0: "Angry", 1: "Disgusted", 2: "Fearful", 3: "Happy", 4: "Neutral", 5: "Sad", 6: "Surprised"}

emotionlistforadding=['Angry','Disgusted','Fearful','Happy','Neutral','Sad','Surprised']
# load model architecture and weights
cap = cv2.VideoCapture(0)
while True:
    ret,image=cap.read()# captures frame and returns boolean value and captured image
    print('hello')
    if not ret:
        continue
    gray_frame = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Image size is reduced by 30% at each image scale.
    scaleFactor = 1.3

# 5 neighbors should be present for each rectangle to be retained.
    minNeighbors = 5

# Detect the Faces in the given Image and store it in faces.
    faces = facec.detectMultiScale(gray_frame, scaleFactor, minNeighbors)

# When Classifier could not detect any Face.
    print(faces)

    for (x, y, w, h) in faces:

        #print(faceBoxes[0][2])
        roi = gray_frame[y:y+h, x:x+w]
        #print(roi)
        roi_new = cv2.resize(roi, (48, 48))
       
        prediction = test_model.predict_emotion(roi_new[np.newaxis, :, :, np.newaxis])
        print(prediction)
        labelemotion= "{}".format("Emotion : " + prediction)
        ##adding the text for showing emotion
        #it is the coordinates of the bottom-left corner of the text string in the image. The coordinates are represented as tuples of two values
        #Font scale factor that is multiplied by the font-specific base size.(0.8)
        #BGR, we pass a tuple.255 0 0
        #gives the type of the line to be used.
        #2 is thickness
        
        y = y - 10 if y - 10 > 10 else y + 10
        cv2.putText(image, labelemotion, (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.8,(0, 255, 255), 2, cv2.LINE_AA)
        #cv2.putText(frame, text, (startX, y),cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 0, 255), 2)
    

	# show the output frame
    cv2.imshow("Frame", image)
    key = cv2.waitKey(1) & 0xFF
 
    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        break

# After the loop release the cap object
vid.release()
# Destroy all the windows
cv2.destroyAllWindows()

hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
[[340 289 188 188]]
Sad
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
()
hello
[[350 297 174 174]]
Sad
hello
()
hello
()
hello
()
hello
[[340 290 183 183]]
Sad
hello
[[336 279 196 196]
 [360 307  61  61]]
Neutral
Happy
hello
[[334 282 196 196]]
Neutral
hello
[[332 279 196 196]]
Neutral
hello
[[336 284 190 190]]
Neutral
hello
()
hello
[[344 282 188 188]]
Neutral
hello
()
hello
()
hello
[[350 290 181 181]]
Neutral
hello
()
hello
()
hello
()
hello
()
hello
[[340 279 196 196]]
Neutral
hello
[[345 282 196 196]]
Neutral
hello
[[343 280 196 196]]
Neutral
hello
[[343 282 196 196]]
Neutral
hello
()
hello
[[353 277 196 196]]
Neutral
hello
[[358 279 190 190]]
Neutral
hello
[[367 278 186 186]]
Neutral
hello
[[369 264 184 184]]
Neutral
hello
[[371 263 178 178]]
Sad
hello
[[363 248 166 166]]
Ne

NameError: name 'vid' is not defined